/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as PullListIndexRouteImport } from './routes/pull-list/index'
import { Route as SettingsIndexersIndexRouteImport } from './routes/settings/indexers/index'
import { Route as SettingsDownloadClientsIndexRouteImport } from './routes/settings/download-clients/index'
import { Route as SeriesSeriesIdIndexRouteImport } from './routes/series/$seriesId/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const PullListIndexRoute = PullListIndexRouteImport.update({
  id: '/pull-list/',
  path: '/pull-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexersIndexRoute = SettingsIndexersIndexRouteImport.update({
  id: '/indexers/',
  path: '/indexers/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDownloadClientsIndexRoute =
  SettingsDownloadClientsIndexRouteImport.update({
    id: '/download-clients/',
    path: '/download-clients/',
    getParentRoute: () => SettingsRoute,
  } as any)
const SeriesSeriesIdIndexRoute = SeriesSeriesIdIndexRouteImport.update({
  id: '/series/$seriesId/',
  path: '/series/$seriesId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/pull-list/': typeof PullListIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/series/$seriesId/': typeof SeriesSeriesIdIndexRoute
  '/settings/download-clients/': typeof SettingsDownloadClientsIndexRoute
  '/settings/indexers/': typeof SettingsIndexersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pull-list': typeof PullListIndexRoute
  '/queue': typeof QueueIndexRoute
  '/series': typeof SeriesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/series/$seriesId': typeof SeriesSeriesIdIndexRoute
  '/settings/download-clients': typeof SettingsDownloadClientsIndexRoute
  '/settings/indexers': typeof SettingsIndexersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/pull-list/': typeof PullListIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/series/$seriesId/': typeof SeriesSeriesIdIndexRoute
  '/settings/download-clients/': typeof SettingsDownloadClientsIndexRoute
  '/settings/indexers/': typeof SettingsIndexersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/pull-list/'
    | '/queue/'
    | '/series/'
    | '/settings/'
    | '/series/$seriesId/'
    | '/settings/download-clients/'
    | '/settings/indexers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pull-list'
    | '/queue'
    | '/series'
    | '/settings'
    | '/series/$seriesId'
    | '/settings/download-clients'
    | '/settings/indexers'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/pull-list/'
    | '/queue/'
    | '/series/'
    | '/settings/'
    | '/series/$seriesId/'
    | '/settings/download-clients/'
    | '/settings/indexers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  PullListIndexRoute: typeof PullListIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  SeriesSeriesIdIndexRoute: typeof SeriesSeriesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-list/': {
      id: '/pull-list/'
      path: '/pull-list'
      fullPath: '/pull-list/'
      preLoaderRoute: typeof PullListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/indexers/': {
      id: '/settings/indexers/'
      path: '/indexers'
      fullPath: '/settings/indexers/'
      preLoaderRoute: typeof SettingsIndexersIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/download-clients/': {
      id: '/settings/download-clients/'
      path: '/download-clients'
      fullPath: '/settings/download-clients/'
      preLoaderRoute: typeof SettingsDownloadClientsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/series/$seriesId/': {
      id: '/series/$seriesId/'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId/'
      preLoaderRoute: typeof SeriesSeriesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsDownloadClientsIndexRoute: typeof SettingsDownloadClientsIndexRoute
  SettingsIndexersIndexRoute: typeof SettingsIndexersIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsDownloadClientsIndexRoute: SettingsDownloadClientsIndexRoute,
  SettingsIndexersIndexRoute: SettingsIndexersIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  PullListIndexRoute: PullListIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  SeriesSeriesIdIndexRoute: SeriesSeriesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
